monitoring:
  interval: 5  # Polling interval in seconds
  thresholds:
    success_rate_drop: 30  # Percentage drop to trigger alert
    minimum_transactions: 5  # Minimum transactions to consider for analysis

  dimensions:
    - name: gateway
      enabled: true
    - name: gateway_method
      enabled: true
    - name: gateway_merchant
      enabled: false

database:
  host: "localhost"
  port: 5432
  user: ""
  password: ""
  dbname: "optimizer_core_live"
  sslmode: "disable"

llm:
  api_key: ""
  model: ""
  endpoint: ""  # Azure OpenAI resource name
  deployment: ""
  api_version: ""
  api_type: "azure"

context_builder:
  github:
    enabled: true
    token: ""  # Add your GitHub token here
    repos: 
      - "razorpay/integrations-go"
    max_commits_per_repo: 10
    lookback_hours: 24
  logs:
    enabled: true
    path: "/var/log/payments"
  experiments:
    enabled: true
    api_url: "https://splitz-lavdeep-offers.dev.razorpay.in/twirp/rzp.splitz.experiment.v1.ExperimentAPI/Get"
    splitz_token: ""
    experiment_ids:
      - id: "OjtvbAFEHmYTnu"
        name: "api_bypass"
        description: "API Bypass experiment"
      - id: "OlZ1ZQRWzSoZuy"
        name: "can_route_reasons_bypass"
        description: "Can Route Reasons Bypass experiment"
      - id: "OsHB7dhiXwTQhD"
        name: "rearch_ramp_allow"
        description: "Rearch Ramp Allow experiment"
      - id: "P7cxDH6hXnXq08"
        name: "enable_cls"
        description: "Enable CLS experiment"
      - id: "P7cuBHbCHIuOWp"
        name: "enable_fee_breakup"
        description: "Enable Fee Breakup experiment"
      - id: "PN91VI5yWzeUFB"
        name: "enable_amount_credit_split"
        description: "Enable Amount Credit Split experiment"
      - id: "OZh2nRpKivTnH6"
        name: "api_ledger_cut_off"
        description: "API Ledger Cut Off experiment"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
