monitoring:
  interval: 5  # Polling interval in seconds
  thresholds:
    success_rate_drop: 5.0  # Percentage drop to trigger alert
    minimum_transactions: 1  # Minimum transactions to consider for analysis

  dimensions:
    - name: gateway
      enabled: true
    - name: gateway_payment_method
      enabled: false
    - name: gateway_merchant
      enabled: false

database:
  host: "localhost"
  port: 5432
  user: ""
  password: ""
  dbname: "optimizer_core_live"
  sslmode: "disable"

llm:
  api_key: ""
  model: ""
  endpoint: ""  # Azure OpenAI resource name
  deployment: ""
  api_version: ""
  api_type: "azure"

context_builder:
  github:
    enabled: true
    token: ""  # Add your GitHub token here
    repos: 
      - "razorpay/integrations-go"
    max_commits_per_repo: 10
    lookback_hours: 24
  logs:
    enabled: true
    path: "/var/log/payments"
  experiments:
    enabled: false
    endpoint: "" 